on:
  push:
    paths:
      - 'src/**'
      - '.eslint*'
      - '.prettierrc.js'

concurrency: ci-${{ github.ref }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 19.0.0
          cache: pnpm
      - name: Install
        run: |
          pnpm i
      - name: Lint
        run: |
          pnpm lint